/*
 * DSLR Trigger is designed to control a DSLR camera to providing accurate
 * start and end exposure times
 * Copyright (C) 2018 - 2019  John Murphy
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package info.johnmurphyastro.dslrtrigger.ui;

import java.text.NumberFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author John Murphy
 */
class SettingsDialog extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
    private UiController uiController;
    
    private NumberFormatter getFormatter(){
        NumberFormat format = NumberFormat.getInstance();
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        return formatter;
    }
    
    /**
     * Creates new form Settings.
     * @param parent
     * @param modal
     */
    SettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    void setController(UiController controller) {
        uiController = controller;
    }
    
    /**
     * @return Shutter open lag.
     */
    int getShutterOpenDelay(){
        Object obj = shutterOpenDelayTextField.getValue();
        if (obj instanceof Number){
            return ((Number)obj).intValue();
        }
        return 0;
    }
    
    /**
     * @return Shutter close lag.
     */
    int getShutterCloseDelay(){
        Object obj = shutterCloseDelayTextField.getValue();
        if (obj instanceof Number){
            return ((Number)obj).intValue();
        }
        return 0;
    }
    
    /**
     * @param delay Shutter open lag.
     */
    void setShutterOpenDelay(int delay){
        shutterOpenDelayTextField.setValue(delay);
    }
    
    /**
     * @param delay Shutter close lag.
     */
    void setShutterCloseDelay(int delay){
        shutterCloseDelayTextField.setValue(delay);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        calibrateShutterOpenDelayButton = new javax.swing.JButton();
        shutterCloseDelayTextField = new JFormattedTextField(getFormatter());
        shutterOpenDelayTextField = new JFormattedTextField(getFormatter());
        calibrateShutterCloseDelayButton = new javax.swing.JButton();

        setTitle("DSLR Trigger Settings");

        closeButton.setText("Apply");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Log file"));

        jLabel4.setText("Name:");

        nameTextField.setText("John Murphy");

        jLabel5.setText("Email:");

        emailTextField.setText("myemail@gmail.com");

        jLabel6.setText("Location (long/lat/height):");
        jLabel6.setToolTipText("e.g. W 002 05.123' / N 52 10.123' / 82 m");

        locationTextField.setText("W 002 05.123' / N 52 10.123' / 82 m");
        locationTextField.setToolTipText("e.g. W 002 05.123' / N 52 10.123' / 82 m");

        jLabel7.setText("CCD/camera:");

        cameraTextField.setText("Canon 300D");

        jLabel8.setText("Telescope / lens (Focal length / focal ratio):");
        jLabel8.setToolTipText("e.g. 50mm at F1.8");

        lensTextField.setText("100mm at F2.8");
        lensTextField.setToolTipText("e.g. 50mm at F1.8");

        jLabel9.setText("Optional Comment:");

        commentTextField.setText("BST");

        tabSeparatedCheckBox.setText("Tab separated data");
        tabSeparatedCheckBox.setToolTipText("Separate column data with a tab or comma character");

        logAllEventsCheckBox.setText("Log all events");
        logAllEventsCheckBox.setToolTipText("Log button press and release times");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailTextField)
                            .addComponent(nameTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cameraTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(commentTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lensTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tabSeparatedCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(logAllEventsCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cameraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lensTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(commentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabSeparatedCheckBox)
                    .addComponent(logAllEventsCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Shutter settings"));

        jLabel1.setText("Shutter open delay compensation / ms:");
        jLabel1.setToolTipText("The shutter button will be pressed this many milliseconds early");

        jLabel2.setLabelFor(shutterCloseDelayTextField);
        jLabel2.setText("Shutter close delay compensation / ms:");
        jLabel2.setToolTipText("The shutter button will be released this number of milliseconds early");

        calibrateShutterOpenDelayButton.setText("Calibrate");
        calibrateShutterOpenDelayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calibrateShutterOpenDelayButtonActionPerformed(evt);
            }
        });

        shutterCloseDelayTextField.setText("30");
        shutterCloseDelayTextField.setToolTipText("The shutter button will be released this number of milliseconds early");
        shutterCloseDelayTextField.setMinimumSize(new java.awt.Dimension(40, 30));
        shutterCloseDelayTextField.setName(""); // NOI18N
        shutterCloseDelayTextField.setPreferredSize(new java.awt.Dimension(40, 30));

        shutterOpenDelayTextField.setText("30");
        shutterOpenDelayTextField.setToolTipText("The shutter button will be released this number of milliseconds early");
        shutterOpenDelayTextField.setMinimumSize(new java.awt.Dimension(40, 30));
        shutterOpenDelayTextField.setName(""); // NOI18N
        shutterOpenDelayTextField.setPreferredSize(new java.awt.Dimension(40, 30));

        calibrateShutterCloseDelayButton.setText("Calibrate");
        calibrateShutterCloseDelayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calibrateShutterCloseDelayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shutterOpenDelayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shutterCloseDelayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calibrateShutterOpenDelayButton)
                    .addComponent(calibrateShutterCloseDelayButton))
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(calibrateShutterOpenDelayButton)
                    .addComponent(shutterOpenDelayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(shutterCloseDelayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calibrateShutterCloseDelayButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(closeButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
        uiController.updateSettings();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void calibrateShutterOpenDelayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calibrateShutterOpenDelayButtonActionPerformed
        uiController.showShutterOpenDelayDialog();
    }//GEN-LAST:event_calibrateShutterOpenDelayButtonActionPerformed

    private void calibrateShutterCloseDelayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calibrateShutterCloseDelayButtonActionPerformed
        JTextArea textArea = new JTextArea("The calibration procedure is described here:\n\n"
                + "http://www.johnmurphyastro.info/software/dslr-trigger/dslr-trigger-help/calibrate-shutter-close-lag\n");
        textArea.setEditable(false);
        JOptionPane.showMessageDialog(this, textArea, "Calibrate shutter close lag", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_calibrateShutterCloseDelayButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calibrateShutterCloseDelayButton;
    private javax.swing.JButton calibrateShutterOpenDelayButton;
    final javax.swing.JTextField cameraTextField = new javax.swing.JTextField();
    private final javax.swing.JButton closeButton = new javax.swing.JButton();
    final javax.swing.JTextField commentTextField = new javax.swing.JTextField();
    final javax.swing.JTextField emailTextField = new javax.swing.JTextField();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    final javax.swing.JTextField lensTextField = new javax.swing.JTextField();
    final javax.swing.JTextField locationTextField = new javax.swing.JTextField();
    final javax.swing.JCheckBox logAllEventsCheckBox = new javax.swing.JCheckBox();
    final javax.swing.JTextField nameTextField = new javax.swing.JTextField();
    private javax.swing.JFormattedTextField shutterCloseDelayTextField;
    private javax.swing.JFormattedTextField shutterOpenDelayTextField;
    final javax.swing.JCheckBox tabSeparatedCheckBox = new javax.swing.JCheckBox();
    // End of variables declaration//GEN-END:variables

}
